# Generated by Django 4.1.4 on 2024-07-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='priority',
            field=models.CharField(max_length=255),
        ),
    ]
